name = "Test Mode on GCP"

[api]
port = 80

[asset]
prefix = "https://storage.googleapis.com/lightning-school-uploads"
useGCS = true
GCSBucket = "lightning-school-uploads"
# https://storage.googleapis.com/lightning-school-uploads

[db]
host = "localhost"
port = 3306
user = "developer"
password = "password"
dbname = "development"
